### ISSUE TITLE
[Question] Gear selection not possible

### ISSUE THREAD

**Issue by SeppDE** [darthmaim/gw2builds#75]
Hey there, is it possible that gear selection isn't implemented? 

![grafik](https://user-images.githubusercontent.com/7773216/176556216-7aabf2d6-263f-42ad-8b4f-f074c36825ff.png)

**Comment by darthmaim** [comment]
Yep, gear isn't implemented yet. You can see whats done already in #6 ([preview](https://deploy-preview-6--gw2builds.netlify.app/AAAAAAA)).
